name: data-carpentry
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - fastqc
  - trimmomatic
  - bwa=0.7.17
  - samtools=1.9
  - bcftools=1.9
  - snakemake
  - multiqc
  - fastqc
